### ISSUE TITLE
The version of torch and torch_geometric in your code env.

### ISSUE THREAD

**Issue by LN-Curiosity** [Anwar-Said/Graph2Seq#1]
Hi, @Anwar-Said 
Now the version of my torch_geometric doesn't match the one of your env.
So can you list the version of torch_geometric  and the related py-lib versions?

**Comment by Anwar-Said** [comment]
versions have been added. Thanks

**Comment by LN-Curiosity** [comment]
First, thanks for this project. But the code has some difference with the implementation of the original paper. The decode model outputs seq, but this one outputs a result of multiple classifications. If you need a seq output, you may change a part of the decode model and label data format.
