### ISSUE TITLE
Cannot reproduce the result from test set

### ISSUE THREAD

**Issue by Natqwq** [Anwar-Said/Graph2Seq#2]
Hi,

I couldn't find a way in the code to reproduce the test acc 99+% you published in your implementation paper on the test set. And I can only get about 50% test acc.

Can you please instruct me on how to reproduce it?

Thanks.

**Comment by Natqwq** [comment]
I just find that the initial lr is too small， and I get about 95% acc after increase the lr.

**Comment by Anwar-Said** [comment]
Try adjusting the hyper-parameters and you should be good in reproducing the results.
